[window_mode]
width = 1800
height = 1200
borderless = false
fullscreen_type = "Windowed"
min_width = 0
min_height = 0
max_width = 0
max_height = 0
visible = true
maximized = false
resizable = false
resize_on_scale_factor_change = false
[window_setup]
title = ""
icon = ""
samples = "One"
srgb = false
vsync = true
[backend]
type = "OpenGL"
major = 3
minor = 2
[modules]
gamepad = true
audio = false
