pub mod base_plugins;
pub mod camera_plugin;
pub mod goal_couple_plugin;
pub mod goal_plugin;
pub mod one_holding_switchable_nr_couple_plugin;
pub mod path_plugin;
pub mod pause_plugin;
pub mod status_bar_plugin;
pub mod switchable_nr_plugin;
